services:
  caddy:
    image: caddy:2-alpine
    restart: always
    depends_on:
      - server
    ports:
      - "4000:4000"
    volumes:
      - caddy_data:/data/caddy
      - "./Caddyfile:/etc/caddy/Caddyfile"
  redis:
    image: redis:4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  server:
    image: letmeupgradeya/sonos-proxy:server
    restart: always
    build:
      context: .
    depends_on:
      - redis
    command: npm start
    environment:
      NODE_ENV: development
      START_NODE_OPTIONS: >-
        --enable-source-maps --unhandled-rejections=strict --inspect=0.0.0.0:9229
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 5001:5001
      - 9229:9229
volumes:
  caddy_data:
  redis_data:
networks:
  sonos-proxy:
    external: true
