version: "3.6"
services:
  sonos-proxy-caddy:
    image: caddy
    restart: always
    depends_on:
      - sonos-proxy
    ports:
      - "5000:5000"
    volumes:
      - caddy_data:/data/caddy
      - "./Caddyfile:/etc/caddy/Caddyfile"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  sonos-proxy:
    image: sonos-proxy:server
    build:
      context: .
    depends_on:
      - redis
    command: npm start
    environment:
      NODE_ENV: development
      # AWS_REGION: us-east-1
      # REDIS_CONFIG: |
      #   - host: redis
      #   - port: 7000
      START_NODE_OPTIONS: >-
        --enable-source-maps --unhandled-rejections=strict

    ports:
      - 5001:5001
volumes:
  caddy_data:
  redis_data:
networks:
  default:
    external:
      name: sonos-proxy
